### ISSUE TITLE
No improvement with pre-trained REBEL model on CONLL04

### ISSUE THREAD

**Issue by ramarasty** [Babelscape/rebel#10]
Thanks for your work. I tried to train on CONLL04, and it works as expected with BART, but with the REBEL-Large model, all the scores stay at 0.
I know there is an issue with transformers 4.4.0, and my experiments were conducted with pytorch 1.7.1 and transformers 4.12.4 (no change to datasets or any other package).
Have I been doing something wrong? If there is no other solution, is it possible to get an updated version of the model? If not, could I ask for the finetuned CONLL04 model with REBEL pretraining?

**Comment by ramarasty** [comment]
Thank you for the detailed response.
I did try different seeds. Adding the head/tail pairs to `additional_special_tokens` did not help either.

I wasn't sure if you meant this `added_tokens.json` file was generated after training CONLL04 on REBEL-Large or if you meant I should replace the one that comes with REBEL-Large. I tried changing that, but it still didn't work.

**Comment by LittlePea13** [comment]
It is the file that the trained model for CONLL04 generates for the tokenizer so you could compare it and see if there was something wrong. 

I have tested the same from my end, with the previous `additional_special_tokens` and adding the `<head>` and `<tail>` ones. I think I know what is happening. From my end, without those tokens, I run into the same issue as you (due to the fact the special tokens get mapped to incorrect IDs), but when I added the fix I suggested, it worked and I get good performance again. However, **I had to remove the cached datasets that were generated before**. So if I am correct, this does fix the issue, you just have to delete the cached datasets first in the data folder (or specify not to load them from cache). 

Sorry for the inconvenience, if you end up fixing it, please let me know. It trained fine on my end, which sounds as an empty statement, so I would like to get it fixed for your end as well.

If you confirm I will update the code with those tokens, and add a comment specifying that if training REBEL from scratch they can be ignored, but to finetune over the existing one they are needed.

**Comment by ramarasty** [comment]
It worked!

Thank you so much. I thought there was no cache after each colab session, but overwriting the cache fixed it.

**Comment by David-Lee-1990** [comment]
@ramarasty hi,  do you get F1=75.4 on Conll04?  I tried 5 seeds but only get around 73.6.

**Comment by ramarasty** [comment]
Hi @David-Lee-1990. I did not pre-train on REBEL. My best result is 71.28

**Comment by David-Lee-1990** [comment]
> Hi @David-Lee-1990. I did not pre-train on REBEL. My best result is 71.28

have you tried to load 'Babelscape/rebel-large'  on Conll04? 

@LittlePea13  could we just load 'Babelscape/rebel-large'  on experiments to get rebel_pretraining based model's performances?

**Comment by ramarasty** [comment]
Sorry, I did have a test:

```
Best Pretrained on REBEL dataset:

processed 288 sentences with 421 relations; found: 398 relations; correct: 306.
	ALL	 TP: 306;	FP: 83;	FN: 100
		(m avg): precision: 78.66;	recall: 75.37;	f1: 76.98 (micro)
		(M avg): precision: 80.28;	recall: 76.82;	f1: 78.46 (Macro)

	killed by: 	TP: 42;	FP: 4;	FN: 5;	precision: 91.30;	recall: 89.36;	f1: 90.32;	46
	residence: 	TP: 74;	FP: 25;	FN: 24;	precision: 74.75;	recall: 75.51;	f1: 75.13;	99
	location: 	TP: 63;	FP: 14;	FN: 26;	precision: 81.82;	recall: 70.79;	f1: 75.90;	77
	headquarters location: 	TP: 68;	FP: 27;	FN: 28;	precision: 71.58;	recall: 70.83;	f1: 71.20;	95
	employer: 	TP: 59;	FP: 13;	FN: 17;	precision: 81.94;	recall: 77.63;	f1: 79.73;	72
Testing: 100% 18/18 [00:22<00:00,  1.27s/it]
--------------------------------------------------------------------------------
DATALOADER:0 TEST RESULTS
{'test_F1_micro': 76.98113207547169,
 'test_loss': 0.20332060754299164,
 'test_prec_micro': 78.66323907455013,
 'test_recall_micro': 75.36945812807882}
--------------------------------------------------------------------------------
```

Yes, you can load the provided model. I'm not sure why you are getting worse results though.

**Comment by David-Lee-1990** [comment]
@ramarasty  ok, thanks for sharing. In fact, i tried to experiment with transformer Trainer package but not pytorch_lightning, but i could not get the same result on conll04. Sorry for bothering.
