### ISSUE TITLE
How to predict entity types

### ISSUE THREAD

**Issue by Buted** [Babelscape/rebel#2]
Thx for your excellent work. 
I read your paper and skipped codes, but I can't find when and where REBEL predicts entity types. 
I see the paper reported `Strict Evaluation`, so I think I missed something. Can u point the corresponding codes for me?

**Comment by LittlePea13** [comment]
Hi there, for the pre-training phase there are no entity types, since we didn't include them in the silver data process.

However, when evaluating on downstream tasks, the model is finetuned and predicts the entity type by use of special tokens. Therefore it depends on which task/dataset specifically you refer to. 

For instance, in CONLL04, 4 special tokens are added, <peop>, <org>, <other> and <loc> which are used in place of the <subj>, <obj> tokens that surround decoded entities: https://github.com/Babelscape/rebel/blob/2a89e1a50f4701fdf6563bcb6a8b7f137e2dafbb/src/train.py#L80)

Therefore a triplet instance looks like this: <triplet> Richard C. Wallace <peop> Pittsburgh <loc> residence.

If you need REBEL to predict entity types, you would need to finetune it on your own dataset or any of the benchmarks reported in the paper. 

Hope this helps!

**Comment by Buted** [comment]
Your explanation answers my question. Thx for your kind answer :)
