### ISSUE TITLE
How do I know which original span a predicted entity refers to?

### ISSUE THREAD

**Issue by JulianNeuberger** [Babelscape/rebel#57]
Hi there,

I would like to use your fantastic work for my own research, but ran into a problem:
When I predict entities and relations in some text using your model, it produces predictions in the form of 

```json
{
  "head": "some head entity",
  "head_type": "NER_TAG 1",
  "type": "RELATION_TYPE_1",
  "tail": "a tail entity",
  "tail_type": "NER_TAG_2"
}
```

Lets say my input text was 

_"In this text **some head entity** points to a tail entity, but there might also be **some head entity**, that confuses the model"._

How can I now know which of those to spans above the model detected as head of the predicted relation?
Thank you very much for your input!

Cheers,
Julian

**Comment by LittlePea13** [comment]
Hi @JulianNeuberger, what you point out is one of the main shortcomings of REBEL as an end2end system. Since it just decodes the triplets, there is no way to solve that ambiguity.

You could check the cross-attention values, which I think would correlate with the correct span, but that may be a bit technical for some. Other systems like [TANL](https://github.com/amazon-science/tanl) reconstruct all the input. Therefore you don't face this issue, however, reconstructing the whole input is computationally more expensive, and with REBEL, you get a more efficient generation by just generating the triplets present in the input.

Hope this helps :)

**Comment by JulianNeuberger** [comment]
Hi @LittlePea13, thank you for the detailed response and pointers, I will definitely check them out. Maybe the tradeoff could be worth it, but I'll also look into post processing options / heuristics to solve the ambiguity using your approach. 
Thanks again for your clarifications!
