### ISSUE TITLE
Guide to Fine-tuning on Spacy

### ISSUE THREAD

**Issue by carrtesy** [Babelscape/rebel#61]
Hello,
Thanks for your great work. 

Can I ask a guide to fine-tune with spacy interface?
We plan to have dataset annotated with tagtog (https://www.tagtog.com/).
Format is as follows (in json)

```json
{
"relations":
[
{"classId":"r_7"
"entities":["s1v1|e_1|129,134","s1v1|e_2|138,141"],
]
}
```

r_7 is relation id, and e_1 and e_2 are entity id. (129,134) and (138,141) is span index. 

I have successfully gotten zero-shot inference results following your code:
```python
import spacy

nlp = spacy.load("en_core_web_sm")
nlp.add_pipe("rebel", after="senter")

input_sentence = "Gràcia is a district of the city of Barcelona, Spain. It comprises the neighborhoods of Vila de Gràcia, Vallcarca i els Penitents, El Coll, La Salut and Camp d'en Grassot i Gràcia Nova. Gràcia is bordered by the districts of Eixample to the south, Sarrià-Sant Gervasi to the west and Horta-Guinardó to the east. A vibrant and diverse enclave of Catalan life, Gràcia was an independent municipality for centuries before being formally annexed by Barcelona in 1897 as a part of the city's expansion."                 
doc = nlp(input_sentence)

for value, rel_dict in doc._.rel.items():
    print(f"{value}: {rel_dict}")
```
 However, I wonder how can I fine-tune with my dataset, preferably using spacy interface.
Could you give me a guide for this?

Thanks in advance!

**Comment by LittlePea13** [comment]
Hello there! 

Very cool that you decided to use REBEL on some tagged data. Unfortunately,I am unaware of a training script for seq2seq in Spacy using BART. Instead you will have to rely on this repo or any other trainer for seq2seq models, such as [HF trainer](https://huggingface.co/docs/transformers/main_classes/trainer) or [Classy](https://sunglasses-ai.github.io/classy/). In any case, the most important part is preparing your data accordingly. If you plan to use this repo for training, you can check the example for the CONLL04 dataset in this repo.

The main idea is that you end up having a dataset made of input/output text with:

Input: The source text with e_1 and e_2
Output: <triplet> e_1 <subj> e_2 <obj> r_7 ... Following the format explained in the REBEL paper. You should use natural text for your relation types, so rather than r_7 use "located at" or something like that. Also check how to properly create these samples if there is more than one relation in your text. It is properly explained in the paper, and the dataset files have several examples on how to do this.

You should train on top of REBEL so if you use an external trainer (HF or classy) just specify as model name Babelscape/rebel-large instead of let's say facebook/bart-large. If you use this repo just use the training on top of CONLL04 as example in the conf files.

Best of luck!

**Comment by carrtesy** [comment]
Thanks a lot for your kind reply, I appreciate your help!
Have a wonderful day!
